### ISSUE TITLE
install does not work - says out of disk space yet i hve 200GB+ free

### ISSUE THREAD

**Issue by blainejt** [jaysonragasa/MultiRDPClient.NET#1]
the installer gets error message that out of disk space but i have over 200GB free

![image](https://user-images.githubusercontent.com/3649498/81857941-9472bf80-9528-11ea-8294-abba864b5b0a.png)

here is the details:
PLATFORM VERSION INFO
	Windows 			: 10.0.18363.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.3752.0 built by: NET48REL1
	clr.dll 			: 4.8.4150.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.3752.0 built by: NET48REL1
	dfshim.dll 			: 10.0.18362.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///E:/xxxxxxx/Desktop/MultiRDPClient_NET_2_1/MultiRemoteDesktopClient.application
	Application url			: file:///E:/xxxxxxx/Desktop/MultiRDPClient_NET_2_1/Application%20Files/MultiRemoteDesktopClient_1_0_0_0/MultiRemoteDesktopClient.exe.manifest

IDENTITIES
	Deployment Identity		: MultiRemoteDesktopClient.application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8bf8a474d22c6b48, processorArchitecture=msil
	Application Identity		: MultiRemoteDesktopClient.exe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8bf8a474d22c6b48, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of E:\xxxxxxx\Desktop\MultiRDPClient_NET_2_1\MultiRemoteDesktopClient.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///E:/xxxxxxx/Desktop/MultiRDPClient_NET_2_1/Application Files/MultiRemoteDesktopClient_1_0_0_0/MagicLibrary.dll.deploy did not succeed.
		+ The file 'C:\Users\uuuuuuu\AppData\Local\Temp\Deployment\C2B3LBDN.587\H8DKD2MK.B8C\MagicLibrary.dll' already exists.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [5/13/2020 14:44:33] : Activation of E:\xxxxxxx\Desktop\MultiRDPClient_NET_2_1\MultiRemoteDesktopClient.application has started.
	* [5/13/2020 14:44:33] : Processing of deployment manifest has successfully completed.
	* [5/13/2020 14:44:33] : Installation of the application has started.
	* [5/13/2020 14:44:33] : Processing of application manifest has successfully completed.
	* [5/13/2020 14:44:36] : Found compatible runtime version 2.0.50727.
	* [5/13/2020 14:44:36] : Detecting dependent assembly Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil using Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil.
	* [5/13/2020 14:44:36] : Detecting dependent assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [5/13/2020 14:44:36] : Detecting dependent assembly WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=msil using WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=msil.
	* [5/13/2020 14:44:36] : Detecting dependent assembly System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [5/13/2020 14:44:36] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [5/13/2020 14:44:37] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///E:/xxxxxxx/Desktop/MultiRDPClient_NET_2_1/Application Files/MultiRemoteDesktopClient_1_0_0_0/MagicLibrary.dll.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.IO.IOException
		- The file 'C:\Users\uuuuuuu\AppData\Local\Temp\Deployment\C2B3LBDN.587\H8DKD2MK.B8C\MagicLibrary.dll' already exists.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by jaysonragasa** [comment]
Thanks. Some issues with the publisher. See if this works for you  
[https://github.com/jaysonragasa/MultiRDPClient.NET/releases/tag/2.2](https://github.com/jaysonragasa/MultiRDPClient.NET/releases/tag/2.2)

**Comment by Zerglrisk** [comment]
the plobelm fixed over 2.2

**Comment by blainejt** [comment]
That unzips and runs find
